ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "2.2.4"
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.17.0"
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/hadialqattan/pycln
    rev: "v2.4.0"
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: "1.21.0"
    hooks:
      - id: django-upgrade
        args: [--target-version, "3.2"]
