blank_issues_enabled: false
contact_links:
  - name: Questions, Features, etc.
    url: https://github.com/Archmonger/ServeStatic/discussions
    about: Use GitHub Discussions to request features, ask questions, and share ideas.
