name: Issues
description: Report an issue issue or problem with this package.
body:
  - type: input
    id: python_version
    attributes:
      label: Python Version
      placeholder: 3.9.0
    validations:
      required: false
  - type: input
    id: django_version
    attributes:
      label: Django Version
      placeholder: 6.10.0
    validations:
      required: false
  - type: input
    id: package_version
    attributes:
      label: Package Version
      placeholder: 1.0.0
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a detailed explanation of your issue. If necessary, include steps on how to reproduce it.
    validations:
      required: true
