name: Publish Release Docs

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
                  cache: pip
            - name: Install dependecies
              run: |
                  pip install --upgrade hatch uv
            - name: Publish ${{ github.event.release.name }} Docs
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  hatch run docs:deploy_latest ${{ github.event.release.name }}
        concurrency:
            group: publish-docs
