name: Test Docs

on:
    pull_request:
        branches:
            - main
    schedule:
        - cron: "0 0 * * *"

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
                  cache: pip
            - name: Install dependecies
              run: |
                  pip install --upgrade hatch uv
            - name: Check documentation links
              run: |
                  hatch run docs:linkcheck
            - name: Check docs build
              run: |
                  hatch run docs:build
